---
Name: symbiote-datefields
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_javascript:
    - 'symbiote/symbiote-datefields:client/javascript/bootstrap-datepicker.js'
    - 'symbiote/symbiote-datefields:client/javascript/datepicker.js'
  extra_requirements_css:
    - 'symbiote/symbiote-datefields:client/css/bootstrap-datepicker.css'
